name: Validate packages

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-26.04
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/build-test
      - name: Upload validated packages
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v7
        with:
          name: validated-packages
          path: dist/x86_64/*.pkg.tar.zst
          if-no-files-found: error
          retention-days: 1
